added branch original

diff --git a/bin/uberspace-install-pecl b/bin/uberspace-install-pecl
--- a/bin/uberspace-install-pecl
+++ b/bin/uberspace-install-pecl
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 ########################################################################
 #
 # 2011-09-26
@@ -74,20 +74,20 @@ phpize      || error "phpize failed"
 ./configure || error "./configure failed"
 make        || error "make failed"
 
-if [ ! -f ~/.etc/php.ini ] ; then
+if [ ! -f ~/etc/php.ini ] ; then
   PHPLIBDIR=`php --ini | head -1 | awk -F ": " '{ print $2 }'`
-  echo -n "Copying $PHPLIBDIR/php.ini to ~/.etc ... "
-  cp -a $PHPLIBDIR/php.ini ~/.etc/ || error "Copying $PHPLIBDIR/php.ini failed"
+  echo -n "Copying $PHPLIBDIR/php.ini to ~/etc ... "
+  cp -a $PHPLIBDIR/php.ini ~/etc/ || error "Copying $PHPLIBDIR/php.ini failed"
   echo "done"
 fi
 
-EXT_DIR=`grep ^extension_dir ~/.etc/php.ini | sed 's/.*= *//' | sed 's/"//g'`
+EXT_DIR=`grep ^extension_dir ~/etc/php.ini | sed 's/.*= *//' | sed 's/"//g'`
 
 # case: "unconfigured extension_dir"
 if [ "$EXT_DIR" = "" ] ; then
   EXT_DIR=$HOME/pecl
   echo -n "Configuring your extension_dir to $EXT_DIR ... "
-  echo "extension_dir = $EXT_DIR" >> ~/.etc/php.ini
+  echo "extension_dir = $EXT_DIR" >> ~/etc/php.ini
   echo "done"
 fi
 
@@ -95,7 +95,7 @@ fi
 if [ "$EXT_DIR" = "./" ] ; then
   EXT_DIR=$HOME/pecl
   echo -n "Changing your extension_dir to $EXT_DIR ... "
-  perl -pi -e "s|^extension_dir.*|extension_dir = $EXT_DIR|" ~/.etc/php.ini
+  perl -pi -e "s|^extension_dir.*|extension_dir = $EXT_DIR|" ~/etc/php.ini
   echo "done"
 fi
 
@@ -112,8 +112,8 @@ cp -a $MODULES $EXT_DIR || error "Installing $MODULES to $EXT_DIR failed"
 echo "done"
 
 for MODULE in $MODULES ; do
-  echo -n "Activating $MODULE in ~/.etc/php.ini ... "
-  echo "extension=$MODULE" >> ~/.etc/php.ini
+  echo -n "Activating $MODULE in ~/etc/php.ini ... "
+  echo "extension=$MODULE" >> ~/etc/php.ini
   echo "done"
 done
 
diff --git a/bin/uberspace-setup-couchdb b/bin/uberspace-setup-couchdb
--- a/bin/uberspace-setup-couchdb
+++ b/bin/uberspace-setup-couchdb
@@ -1,10 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 ########################################################################
-#
-# 2011-03-24
-# Jonas Pasche
-# jpasche@jonaspasche.com
-#
+# 2014-07-29 Moritz Werner mwerner@jonaspasche.com
 ########################################################################
 #
 #	This program is free software: you can redistribute it and/or modify
@@ -39,7 +35,7 @@ if [ ! -d ~/service ] ; then
   exit 2
 fi
 
-for DIR in ~/couchdb ~/.service/couchdb ~/.etc/run-couchdb ; do
+for DIR in ~/couchdb ~/service/couchdb ~/etc/run-couchdb ; do
   if [ -d $DIR ] ; then
     echo "You already have a $DIR directory. Nothing to do here."
     exit 3
@@ -56,27 +52,77 @@ COUCHDB_USER="`id -un`_couchadmin"
 COUCHDB_PASS=`apg -n 1`
 
 # create couchdb.ini
-echo "Creating the ~/couchdb.ini configuration file"
-sed -r "s/\/var\/(lib|log)/\/home\/$USER/; s/5984/$COUCHDB_PORT/; s/require_valid_user = .*/require_valid_user = true/;" < /etc/couchdb/default.ini > ~/couchdb.ini
+cat <<__EOF__ > ~/couchdb.ini
+[couchdb]
+database_dir = /home/$USER/couchdb
+view_index_dir = /home/$USER/couchdb
+uri_file = /home/$USER/couchdb/couch.uri
 
-# the password automatically gets replaces by a hashed string upon the first CouchDB start!
-cat <<__EOF__ >> ~/couchdb.ini
+[log]
+file = /home/$USER/couchdb/couch.log
+
+[httpd]
+port = $COUCHDB_PORT
 
 [admins]
 $COUCHDB_USER = $COUCHDB_PASS
+
+[couch_httpd_auth]
+require_valid_user = true
 __EOF__
 
-# replaced duplicate create-service-code here
-uberspace-setup-service couchdb couchdb -n -a $HOME/couchdb.ini
+# create the couchdb service run script
+echo "Creating the ~/etc/run-couchdb/run service run script"
+mkdir ~/etc/run-couchdb
+cat <<__EOF__ > ~/etc/run-couchdb/run
+#!/bin/sh
+export HOME=$HOME
+export COUCHPATH="/package/host/localhost/couchdb-1.5/"
+
+exec \$COUCHPATH/bin/couchdb -n -a \$COUCHPATH/etc/couchdb/default.ini -a $HOME/couchdb.ini 2>&1
+__EOF__
+chmod 755 ~/etc/run-couchdb/run
+
+# create the couchdb logging run script
+echo "Creating the ~/etc/run-couchdb/log/run logging run script"
+mkdir ~/etc/run-couchdb/log
+cat <<__EOF__ > ~/etc/run-couchdb/log/run
+#!/bin/sh
+exec multilog t ./main
+__EOF__
+chmod 755 ~/etc/run-couchdb/log/run
+
+echo "Symlinking ~/etc/run-couchdb to ~/service/couchdb to start the service"
+ln -s ../etc/run-couchdb ~/service/couchdb
+
+WAIT=0
+echo -n "Waiting for the service to start ..."
+while [ $WAIT -lt 6 ]; do
+  WAIT=$(($WAIT+1))
+  echo -n " $WAIT"
+  svok ~/service/couchdb 2>/dev/null
+  SVOK=$?
+  if [ "$SVOK" = "0" ] ; then
+    break
+  fi
+  sleep 1
+done
+
+if [ "$SVOK" != "0" ] ; then
+  echo " failed :-("
+  echo "We're really sorry; this shouldn't have happened - please contact hallo@uberspace.de for help. Thanks a lot!"
+  exit 4
+fi
 
 # final information
 echo
 echo "Congratulations - You can now reach your dedicated CouchDB installation!"
 echo "Please note that your CouchDB uses the NON-standard port number $COUCHDB_PORT."
-echo "This allows running multiple instances of CouchDB on the same machine for different users."
 echo
 echo "Hostname: localhost"
-echo "Portnum#: $COUCHDB_PORT"
+echo " Portnum: $COUCHDB_PORT"
 echo "Username: $COUCHDB_USER"
 echo "Password: $COUCHDB_PASS"
-echo
+echo ""
+echo "Settings: $HOME/couchdb.ini"
+echo " Logfile: /home/$USER/couchdb/couch.log"
diff --git a/bin/uberspace-setup-mongodb b/bin/uberspace-setup-mongodb
--- a/bin/uberspace-setup-mongodb
+++ b/bin/uberspace-setup-mongodb
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 ########################################################################
 #
 # 2011-03-03
@@ -33,13 +33,13 @@ if [ "$MY_UID" = "0" ] ; then
   exit 1
 fi
 
-if [ ! -d ~/.service ] ; then
+if [ ! -d ~/service ] ; then
   echo "You need to have a working ~/service directory first to run your own daemons."
   echo "Please run \"uberspace-setup-svscan\" to initialize it before setting up MongoDB."
   exit 2
 fi
 
-for DIR in ~/mongodb ~/.service/mongodb ~/.etc/run-mongodb ; do
+for DIR in ~/mongodb ~/service/mongodb ~/etc/run-mongodb ; do
   if [ -d $DIR ] ; then
     echo "You already have a $DIR directory. Nothing to do here."
     exit 3
@@ -55,8 +55,47 @@ MONGODB_PORT=$((20000 + $MY_UID))
 MONGODB_USER="`id -un`_mongoadmin"
 MONGODB_PASS=`apg -n 1`
 
-# installing mongodb service
-uberspace-setup-service mongodb mongod --dbpath ~/mongodb --bind_ip 127.0.0.1 --port $MONGODB_PORT --auth --nohttpinterface
+# create the mongo service run script
+echo "Creating the ~/etc/run-mongodb/run service run script"
+mkdir ~/etc/run-mongodb
+cat <<__EOF__ > ~/etc/run-mongodb/run
+#!/bin/sh
+exec mongod --dbpath ~/mongodb --bind_ip 127.0.0.1 --port $MONGODB_PORT --auth --nohttpinterface 2>&1
+__EOF__
+chmod 755 ~/etc/run-mongodb/run
+
+# create the mongo logging run script
+echo "Creating the ~/etc/run-mongodb/log/run logging run script"
+mkdir ~/etc/run-mongodb/log
+cat <<__EOF__ > ~/etc/run-mongodb/log/run
+#!/bin/sh
+exec multilog t ./main
+__EOF__
+chmod 755 ~/etc/run-mongodb/log/run
+
+echo "Symlinking ~/etc/run-mongodb to ~/service/mongodb to start the service"
+ln -s ../etc/run-mongodb ~/service/mongodb
+
+WAIT=0
+echo -n "Waiting for the service to start ..."
+while [ $WAIT -lt 6 ]; do
+  WAIT=$(($WAIT+1))
+  echo -n " $WAIT"
+  svok ~/service/mongodb 2>/dev/null
+  SVOK=$?
+  if [ "$SVOK" = "0" ] ; then
+    break
+  fi
+  sleep 1
+done
+
+if [ "$SVOK" != "0" ] ; then
+  echo " failed :-("
+  echo "We're really sorry; this shouldn't have happened - please contact hallo@uberspace.de for help. Thanks a lot!"
+  exit 4
+fi
+
+echo " started!"
 
 # Creating the administrative user
 echo "Creating administrative user"
diff --git a/sbin/uberspace-account-common b/sbin/uberspace-account-common
--- a/sbin/uberspace-account-common
+++ b/sbin/uberspace-account-common
@@ -61,4 +61,124 @@ function noconfig ()
 	exit 1;
 }
 
-# no ftp. kthx
+function removefromftpusers ()
+{
+grep -e "^${USERNAME}$" /etc/vsftpd/ftpusers;
+ISBLOCKED1=$?;
+if [ "${ISBLOCKED1}" == "1" ]; then
+	echo "User ${USERNAME} is not on FTP blocklist (/etc/vsftpd/ftpusers).";
+elif [ "${ISBLOCKED1}" == "0" ]; then
+	/bin/cp /etc/vsftpd/ftpusers /etc/vsftpd/ftpusers.bak;
+	sed -i -e '/^'"${USERNAME}"'$/d' /etc/vsftpd/ftpusers;
+	echo "Removed User ${USERNAME} from FTP blocklist (/etc/vsftpd/ftpusers).";
+fi
+}
+
+function removefromftpuser_list ()
+{
+grep -e "^${USERNAME}$" /etc/vsftpd/user_list;
+ISBLOCKED2=$?;
+if [ "${ISBLOCKED2}" == "1" ]; then
+	echo "User ${USERNAME} is not on FTP blocklist (/etc/vsftpd/user_list).";
+elif [ "${ISBLOCKED2}" == "0" ]; then
+	/bin/cp /etc/vsftpd/user_list /etc/vsftpd/user_list.bak;
+	sed -i -e '/^'"${USERNAME}"'$/d' /etc/vsftpd/user_list;
+	echo "Removed User ${USERNAME} from FTP blocklist (/etc/vsftpd/user_list).";
+fi
+}
+
+function addtoftpusers ()
+{
+grep -e "^${USERNAME}$" /etc/vsftpd/ftpusers;
+ISBLOCKED1=$?;
+if [ "${ISBLOCKED1}" == "0" ]; then
+	echo "User ${USERNAME} is already on FTP blocklist (/etc/vsftpd/ftpusers).";
+elif [ "${ISBLOCKED1}" == "1" ]; then
+	/bin/cp /etc/vsftpd/ftpusers /etc/vsftpd/ftpusers.bak;
+	echo ${USERNAME} >> /etc/vsftpd/ftpusers;
+	echo "Added User ${USERNAME} to FTP blocklist (/etc/vsftpd/ftpusers).";
+fi
+}
+
+function addtoftpuser_list ()
+{
+grep -e "^${USERNAME}$" /etc/vsftpd/user_list;
+ISBLOCKED2=$?;
+if [ "${ISBLOCKED2}" == "0" ]; then
+	echo "User ${USERNAME} is already on FTP blocklist (/etc/vsftpd/user_list).";
+elif [ "${ISBLOCKED2}" == "1" ]; then
+	/bin/cp /etc/vsftpd/user_list /etc/vsftpd/user_list.bak;
+	echo ${USERNAME} >> /etc/vsftpd/user_list;
+	echo "Added User ${USERNAME} to FTP blocklist (/etc/vsftpd/user_list).";
+fi
+}
+
+function sanitize_hostname () {
+
+  ETLDDAT=/etc/effective_tld_names.dat
+
+  # convert domain to lowercase and convert to idn (if necessary)
+  THIS_HOSTNAME=`echo "$1" | tr '[:upper:]' '[:lower:]' | idn --quiet`
+
+  if [[ ! ${THIS_HOSTNAME} =~ ^(\*\.)?[a-z0-9][a-z0-9.-]*[a-z0-9]$ ]] ; then
+    echo "Invalid characters in hostname"
+    return 1
+  fi
+
+  if [[ ! ${THIS_HOSTNAME} =~ \.(.+) ]] ; then
+    echo "This hostname has no '.' in it"
+    return 1
+  fi
+
+  # this is the hostname with the first label stripped
+  # so we can match "some.tld" against "*.tld"
+  CHECKPART=${BASH_REMATCH[1]}
+
+  SUCCESS=0
+
+  grep -q -E "^\!${THIS_HOSTNAME}\$" ${ETLDDAT}
+  if [ "$?" = "0" ] ; then
+    SUCCESS=1
+  fi
+
+  grep -q -E "^${THIS_HOSTNAME}\$" ${ETLDDAT}
+  if [ "$?" = "0" ] ; then
+    echo "Uh-oh: You can only use hostnames like 'blah.${THIS_HOSTNAME}', not '${THIS_HOSTNAME}' itself ('${THIS_HOSTNAME}' is an eTLD)."
+    return 1
+  fi
+
+  grep -q -E "^\*\.${CHECKPART}\$" ${ETLDDAT}
+  if [ "$?" = "0" ] ; then
+    echo "Uh-oh: '*.${CHECKPART}' is reserved by the registry; you can only use hostnames under a sub-TLD like 'blah.SUB.${CHECKPART}'."
+    exit 1
+  fi
+
+  while true ; do
+    grep -q -E "^\*\.${CHECKPART}\$" ${ETLDDAT}
+    if [ "$?" = "0" ] ; then
+      SUCCESS=1
+      break
+    fi
+    grep -q -E "^${CHECKPART}\$" ${ETLDDAT}
+    if [ "$?" = "0" ] ; then
+      SUCCESS=1
+      break
+    fi
+    # cut the first label of the hostname
+    if [[ $CHECKPART =~ \.(.+) ]] ; then
+      CHECKPART=${BASH_REMATCH[1]}
+    else
+      echo "Uh-oh: Could not find a valid suffix for ${THIS_HOSTNAME}; you can't use it."
+      return 1
+    fi
+  done
+
+  if [ "$SUCCESS" = "0" ] ; then
+    echo "Uh-oh: I did not foresee how to get here."
+    return 1
+  fi
+
+  echo ${THIS_HOSTNAME}
+  return 0
+}
+
diff --git a/sbin/uberspace-stockup-ipv6-pool b/sbin/uberspace-stockup-ipv6-pool
--- a/sbin/uberspace-stockup-ipv6-pool
+++ b/sbin/uberspace-stockup-ipv6-pool
@@ -1,24 +1,20 @@
-#!/bin/bash
+#!/bin/sh
+########################################################################
+# 2012-04-15 Christopher Hirschmann c.hirschmann@jonaspasche.com
 ########################################################################
 #
-# 2011-04-06
-# Christopher Hirschmann
-# c.hirschmann@jonaspasche.com
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
 #
-########################################################################
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
 #
-#       This program is free software: you can redistribute it and/or modify
-#       it under the terms of the GNU General Public License as published by
-#       the Free Software Foundation, either version 3 of the License, or
-#       (at your option) any later version.
-#
-#       This program is distributed in the hope that it will be useful,
-#       but WITHOUT ANY WARRANTY; without even the implied warranty of
-#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#       GNU General Public License for more details.
-#
-#       You should have received a copy of the GNU General Public License
-#       along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 ########################################################################
 #
@@ -36,12 +32,21 @@
 
 function cantcreate ()
 {
-	echo "Error. Couldn't create $POOLFILE";
+	echo "Error. Couldn't create $POOL";
 	exit 126;
 }
 
-POOLFILE="/etc/ipv6-address-pool/index.txt";
-USAGE="Usage:\n-h\t\tthis help message\n-d ethX\t\tnetwork device\n-f int\t\taddress to start from (1..65534)\n-i file\t\tindex file containing IPv6 address pool index, default: $POOLFILE\n-p 2a02::1234\t\tIPv6 address prefix with last block missing\n-t int\t\taddress to end with (1..65534)\n";
+function cantcreatedir ()
+{
+	echo "Error. Couldn't create $POOLDIR";
+	exit 128;
+}
+
+## this includes host specific variables
+. /usr/local/sbin/uberspace-account-local-settings.sh;
+
+POOL="/etc/ipv6-address-pool/index.txt";
+USAGE="Usage:\n-h\t\tthis help message\n-d ethX\t\tnetwork device\n-f int\t\taddress to start from (1..65534)\n-i file\t\tindex file containing IPv6 address pool index, default: $POOL\n-p 2a02::1234\t\tIPv6 address prefix with last block missing\n-t int\t\taddress to end with (1..65534)\n";
 
 if [ ! $# -ge 1 ];
 then
@@ -64,7 +69,7 @@ while getopts ":hd:f:i:p:t:" Option; do
 			declare -i COUNTFROM=${OPTARG};
 			;;
 		i)
-			POOLFILE=${OPTARG};
+			POOL=${OPTARG};
 			;;
 		p)
 			PREFIX=${OPTARG};
@@ -84,6 +89,8 @@ while getopts ":hd:f:i:p:t:" Option; do
 done
 
 shift $(($OPTIND - 1))
+
+POOLDIR=`dirname $POOL`;
 
 if [ -z $INTERFACE ]; then
 	echo "Error. No interface given.";
@@ -150,15 +157,21 @@ if [ "$CONFIGNOTREADY" == "1" ]; then
 	echo "IPV6ADDR_SECONDARIES=\"\"" >> $CONFIGFILE || exit 123;
 fi
 
+# check if the directory for the pool index file exists, create it if it doesn't
+if [[ ! -d $POOLDIR ]]; then
+	echo "$POOLDIR doesn't exist yet. I'm going to create it.";
+	mkdir -p -m 0700 $POOLDIR || cantcreatedir;
+fi
+
 # check if the IPv6 address pool index file exists, create it if it doesn't.
-if [[ ! -a $POOLFILE ]]; then
-	echo "$POOLFILE doesn't exist yet. I'm going to create it."
-	touch $POOLFILE || cantcreate;
+if [[ ! -a $POOL ]]; then
+	echo "$POOL doesn't exist yet. I'm going to create it."
+	touch $POOL || cantcreate;
 fi
 
 # check if the poolfile is writeable
-if [[ ! -w $POOLFILE ]]; then
-	echo "Error. $POOLFILE isn't writable."
+if [[ ! -w $POOL ]]; then
+	echo "Error. $POOL isn't writable."
 	exit 125;
 fi
 
@@ -167,8 +180,8 @@ fi
 		H=$(printf "%X\n" $COUNTFROM);
 		CURRENTIP=`echo "${PREFIX}:${H}" | tr "[:upper:]" "[:lower:]"`;
 
-# make sure that the address isn't already in the poolfile
-		grep -q "${CURRENTIP} " $POOLFILE;
+# make shure that the address isn't already in the poolfile
+		grep -q "${CURRENTIP} " $POOL;
 		INPOOL=$?;
 		if [ "$INPOOL" == "1" ]; then
 
@@ -176,20 +189,20 @@ fi
 			grep -q "${CURRENTIP}" $CONFIGFILE;
 			INCONFIG=$?;
 			if [ "$INCONFIG" == "1" ]; then
-		
+
 # add address to config
 				sed -i -e 's/IPV6ADDR_SECONDARIES=\"/&'"${CURRENTIP}"' /' $CONFIGFILE;
 # add address to interface
 #				echo "ip -6 addr add ${CURRENTIP}/64 dev ${INTERFACE}";
 				ip -6 addr add ${CURRENTIP}/64 dev ${INTERFACE};
 # add address to pool
-				echo "$CURRENTIP free" >> $POOLFILE;
+				echo "$CURRENTIP free" >> $POOL;
 				((SUCCESSFUL=SUCCESSFUL+1));
 			else
 				echo "Not adding ${CURRENTIP}, because it is already in ${CONFIGFILE}.";
 			fi
 		else
-			echo "Not adding ${CURRENTIP}, because is is already in ${POOLFILE}."
+			echo "Not adding ${CURRENTIP}, because is is already in ${POOL}."
 		fi
 		((COUNTFROM=COUNTFROM+1));
 	done
